# Generated by Django 5.2.12 on 2026-03-18 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento', models.CharField(max_length=10)),
                ('precio', models.DecimalField(decimal_places=2, default=32.0, max_digits=6)),
                ('fecha_compra', models.DateTimeField(auto_now_add=True)),
                ('funcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos', to='cartelera.funcion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cartelera.usuario')),
            ],
        ),
    ]
