# Generated by Django 5.2.12 on 2026-03-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0002_boleto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(choices=[('A', 'Clasificación A'), ('B', 'Clasificación B'), ('C', 'Clasificación C')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='estatus',
            field=models.CharField(choices=[('ESTRENO', 'Estreno'), ('CARTELERA', 'Cartelera'), ('NO_DISPONIBLE', 'No disponible')], default='CARTELERA', max_length=20),
        ),
    ]
