# Generated by Django 5.2.12 on 2026-03-18 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0003_alter_pelicula_clasificacion_alter_pelicula_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='columnas',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='sala',
            name='filas',
            field=models.IntegerField(default=6),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='clasificacion',
            field=models.CharField(choices=[('AA', 'AA'), ('A', 'A'), ('B', 'B'), ('B15', 'B15'), ('C', 'C')], max_length=5),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='estatus',
            field=models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva'), ('PROXIMAMENTE', 'Próximamente')], default='ACTIVA', max_length=20),
        ),
    ]
