# Generated by Django 5.2.12 on 2026-03-19 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0004_sala_columnas_sala_filas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='columnas',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='filas',
        ),
        migrations.AddField(
            model_name='sala',
            name='capacidad',
            field=models.IntegerField(default=50),
        ),
    ]
